### ISSUE TITLE
Unnest success responses

### ISSUE THREAD

**Issue by dmaloneycalu** [vokal/vokal-ng-api#28]
I find myself writing this `.then` inside almost every service API call. It feels very redundant, especially for success responses.
```
return APISrvc.$get( "/something" )
    .then( function ( data )
    {
        return data.data;
    } );
```

Should we include a flag for setup that allows us to 'unwrap' success calls? So we'd setup the API object like:
```
new API( {
    rootPath: APIRoot + "/v1",
    unwrapSuccess: true
} );
```

Wanted to propose this before putting the work in behind it. By setting this default to false, it would not be a breaking change.

**Comment by dmaloneycalu** [comment]
@vokal/web if not everyone is watching this repo

**Comment by Tathanen** [comment]
How would you write a response handler with this flag turned on? I feel like you forgot to finish this thought.

**Comment by dmaloneycalu** [comment]
Oh! It just would remove the need for API requests in the service to have that `.then( function( data ){ return data.data; });` step. So the initial example would become `return APISrvc.$get( "/something" );`

**Comment by Tathanen** [comment]
Oh okay. Probably worth doing. Maybe should return data not data.data tho.  Maybe make the flag returnSuccess. Tho doesn't this discourage error handling?

**Comment by dmaloneycalu** [comment]
@Tathanen I don't think it discourages error handling, it just removes the massaging in success responses.

``` (service.js)
this.getParticularStuff = function ( id )
{
    return APISrvc.$get( "/stuff/id" );
};
```
instead of
``` (service.js)
this.getParticularStuff = function ( id )
{
    return APISrvc.$get( "/stuff/id" )
        .then( function ( res )
        {
            return res.data;
        } );
};
```

My suggestion is specifically for success responses, so error handling would continue to look the same in the controller
``` (controller.js)
StuffSrvc.getParticularStuff( someId )
    .then( function ( res )
    {
        $scope.particularStuff = res;
    }, function ( err )
    {
        if( err.status === 404 )
        {
            toastr.error( "Could not find stuff." );
        }
        else
        {
            toastr.error( "Error communicating with the server." );
        }
    } );
```

**Comment by Tathanen** [comment]
Yeah but this just condenses requests where we don't handle errors. Which, arguably, we should never be writing.

**Comment by dmaloneycalu** [comment]
I think we discussed the poor communication (and hassle) it is to handle API errors in services, so I only see this condensing the success massaging. Code reviews should be ensure there aren't missing error cases.

I'll go ahead and make the modifications for this, presuming it would be a v4.1.0 push.

**Comment by Tathanen** [comment]
If you use this, though, your service no longer returns a promise to be chained to. It returns the success object, and prevents you from appending an error handler, whether it's in your service or controller.

**Comment by dmaloneycalu** [comment]
I'm not saying we remove the promise entirely, I'm saying instead our success resolve should look more like this:

```
deferred.resolve( config.unwrapSuccess ? data : {
    status: status,
    data: data,
    options: options
} );
```

**Comment by Tathanen** [comment]
... I must be missing something, because that's completely different from what you've been proposing so far. Your initial examples remove the "then" handler entirely, and have "$get" return data.data.  Simplifying the value sent via the resolve would still require the "then" to access that value.

**Comment by Tathanen** [comment]
And upon further thought, this doesn't seem like something we'd want applied as a global setting. What I'd recommend is a shortcut method, $getData, that does something like what you're looking for. Otherwise it becomes very difficult for a reviewer to know which requests are returning one way or the other.

**Comment by jrit** [comment]
This seems more confusing to me to save a few characters. <3 from Toronto airport

**Comment by dmaloneycalu** [comment]
@Tathanen My initial example was to remove an unnecessary `.then`, not all of them. Specifically the ones that I've been writing to exclusively 'unwrap' the data before handing it off to the controllers.

Should probably discuss this in person if things are being misconstrued without having a full project structure to demonstrate with.

**Comment by jrit** [comment]
Now that I'm not on a phone, a more complete explanation: I'm really wary of having potentially two interfaces with slightly different behaviors based on configuration that is elsewhere because it requires the consumer to remember how the interface was initialized, which could lead to mistakes in authorship or code review. Also, with arrow functions this could shorten from

```js
.then( function ( res )
{
       return res.data;
} );
```
to
```js
.then(res => res.data);
```

**Comment by dmaloneycalu** [comment]
Going to close this. Two viable alternatives are to convert the multi-line responses into one liners, or to universally address the response in the controllers that are using the call. (I'll probably go with the former because => )
