### ISSUE TITLE
APIRequestUnauthorized should only fire on 401

### ISSUE THREAD

**Issue by Tathanen** [vokal/vokal-ng-api#38]
In a properly built API, 401 means we don't know who you are so maybe you can access this, but 403 means you can't access this no matter what.  As such, redirecting to login for 401 makes sense, but it won't accomplish anything for a 403.

I'd like to make the APIRequestUnauthorized event only fire for 401s, and similarly only respect the unauthorizedInterrupt flag for 401s.  It'll count as a breaking change.

@vokal/web lemme know what you guys think about this, I wanna make sure we're on the same page regarding the proper response to these codes.

**Comment by CMDadabo** [comment]
Yup, that makes sense to me.

**Comment by jrit** [comment]
The 403 assumption would be that maybe you have other creds you can use. Our use of 401s doesn't follow the HTTP spec anyway, though seems to follow convention. I don't necessarily have an objection to changing this, but doing it based on the spec rather than based on practical concerns might not be very useful.

**Comment by Tathanen** [comment]
Said 403 assumption being based on a "maybe" probably isn't good enough reason to force a log-out, is all.  Perhaps an error message that suggests you do that, but it's not a clear 1:1 "I don't know you, please authenticate."

For what it's worth, I am indeed basing this on practical concerns, as while helping Medline define their API spec there ended up being a fair amount of 403s that needed to just display a message, not log the user out.

**Comment by StoicJester** [comment]
Sounds good to me.

**Comment by jrit** [comment]
To be fair, a 401 probably shouldn't force a log out if the 403 shouldn't. Seems reasonable anyway.

**Comment by Tathanen** [comment]
Well if you're getting a 401 you're either already logged out, or you need to renew your token.  But sure, this service shouldn't actually prescribe one solution or another.

**Comment by Tathanen** [comment]
I think I might make the solution to this a little fancier as I'm realizing some issues, stay tuned!!!!

**Comment by Tathanen** [comment]
Attempting resolution in https://github.com/vokal/vokal-ng-api/pull/39

**Comment by Tathanen** [comment]
Closed per v6.0.0 release.
